name: build-docker-images

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push arch image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/arch-dev-gitpod:latest
      -
        name: Build and push arch rust image
        uses: docker/build-push-action@v4
        with:
          context: ./rust
          file: ./rust/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rust-arch-gitpod:latest
      -
        name: Build and push arch java image
        uses: docker/build-push-action@v4
        with:
          context: ./java
          file: ./java/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/java-arch-gitpod:latest
          build-args: |
            JAVA_VERSION=${{ vars.JAVA_VERSION }}
      -
        name: Build and push ubuntu image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.ubuntu
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-dev-gitpod:latest
